export const ROUTE_APP = "/app";

/**** ANALYSES ROUTE ****/
export const ROUTE_APP_ANALYSE = ROUTE_APP + '/analyse';
export const ROUTE_APP_ANALYSE_DASHBOARD = ROUTE_APP_ANALYSE + '/tableau-de-bord';
export const ROUTE_APP_ANALYSE_BI = ROUTE_APP_ANALYSE + '/bi';


/**** MANAGEMENT ROUTE ****/
export const ROUTE_APP_MANAGEMENT= ROUTE_APP + '/management';
export const ROUTE_APP_ADMINISTRATION= ROUTE_APP + '/administration';

export const ROUTE_APP_MANAGEMENT_CHURCH = ROUTE_APP_MANAGEMENT + '/eglises';
export const ROUTE_APP_MANAGEMENT_LOCAL_CHURCH = ROUTE_APP_MANAGEMENT + '/eglises-locales';
export const ROUTE_APP_MANAGEMENT_HOME_CHURCH = ROUTE_APP_MANAGEMENT + '/eglises-de-maison';
export const ROUTE_APP_MANAGEMENT_MEMBER= ROUTE_APP_MANAGEMENT + '/ames';
export const ROUTE_APP_MANAGEMENT_TRAINING = ROUTE_APP_MANAGEMENT + '/formation';
export const ROUTE_APP_MANAGEMENT_EVENTS = ROUTE_APP_MANAGEMENT + '/evenements';
export const ROUTE_APP_MANAGEMENT_EVANGELIZE = ROUTE_APP_MANAGEMENT + '/evangilisation';

export const ROUTE_APP_ADMINISTRATION_STAR = ROUTE_APP_ADMINISTRATION + '/star';
export const ROUTE_APP_ADMINISTRATION_USER = ROUTE_APP_ADMINISTRATION + '/utilisateur';
export const ROUTE_APP_ADMINISTRATION_PASTOR = ROUTE_APP_ADMINISTRATION + '/pasteur';
export const ROUTE_APP_ADMINISTRATION_MINISTRY = ROUTE_APP_ADMINISTRATION + '/ministere';
export const ROUTE_APP_ADMINISTRATION_REM = ROUTE_APP_ADMINISTRATION + '/rem';


/**** COMMUNICATION ROUTE ****/
export const ROUTE_APP_COMMUNICATION= ROUTE_APP + '/communication';
export const ROUTE_APP_COMMUNICATION_INTERFACING = ROUTE_APP_COMMUNICATION + '/interfacage';


      /*** INTERFACING ROUTE ***/
      export const ROUTE_APP_COMMUNICATION_INTERFACING_EXPORT = ROUTE_APP_COMMUNICATION_INTERFACING + '/export';
      export const ROUTE_APP_COMMUNICATION_INTERFACING_IMPORT = ROUTE_APP_COMMUNICATION_INTERFACING + '/import';


export const ROUTE_APP_COMMUNICATION_PCS = ROUTE_APP_COMMUNICATION + '/pcs';



/**** GED ROUTE ****/
export const ROUTE_APP_GED = ROUTE_APP + '/ged';
export const ROUTE_APP_GED_MY_DOCUMENT = ROUTE_APP_GED + '/mes-documents';
export const ROUTE_APP_GED_SHARED_DOCUMENT = ROUTE_APP_GED + '/documents-partages';
export const ROUTE_APP_GED_ARCHIVE = ROUTE_APP_GED + '/archive';
